name: C# CI

on:
  push:
    branches:
      - main
    paths:
      - '**.cs'
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/project.assets.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore --project c#/dependencies/dependencies.csproj

      - name: Build project
        run: dotnet build --configuration Release --project c#/dependencies/dependencies.csproj

      - name: Run tests
        run: dotnet test --configuration Release --no-build
