name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ toolchain
        uses: actions/setup-cpp@v2
        with:
          cpp-version: '17' # Specify the desired C++ version

      - name: Build project
        run: cmake --build . --config Release

      - name: Run tests
        run: ctest --output-on-failure
