name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            # Specify the directories to cache
            <path_to_dependencies_directory>
          key: ${{ runner.os }}-caching-${{ hashFiles('<path_to_dependencies_directory>/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-caching-
            
      - name: Configure
        run: ./configure
      
      - name: Build
        run: make
      
      - name: Run tests
        run: make check
      
      - name: Make distribution check
        run: make distcheck
